# GPT

In [9]:
# Mathematical trick for the self-attention
import torch
torch.manual_seed(1337)
B,T,C = 4,8,2
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [12]:
# We want to x[b,t] = mean_{i<==t} x[b,1]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xbow[b,t] = torch.mean(x[b,:t+1], 0)

In [13]:
x[0]

tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102],
        [ 0.2360, -0.2398],
        [-0.9211,  1.5433]])

In [14]:
xbow[0]

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

In [21]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3,3))
b = torch.randint(0,10,(3,2)).float()
c = a @ b

print('a==')
print(a)
print('---')
print('b==')
print(b)
print('---')
print('c==')
print(c)


a==
tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
---
b==
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
---
c==
tensor([[ 2.,  7.],
        [ 8., 11.],
        [14., 16.]])
